name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Python-Setup
        uses: actions/setup-python@v4
        with:
            python-version: '3.10'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
            publish_dir: dist
            publish_branch: gh-pages
            github_token: ${{ secrets.GITHUB_TOKEN }}
